# Generated by Django 2.2.9 on 2020-01-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notesFields',
            fields=[
                ('id', models.CharField(max_length=5000, primary_key=True, serialize=False)),
                ('note_content', models.CharField(max_length=5000)),
            ],
        ),
    ]
