# Generated by Django 2.2.9 on 2020-01-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notesfields_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesfields',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
